### ISSUE TITLE
[Bug]: incorrect word splitting of testkube --args in entrypoint.sh

### ISSUE THREAD

**Issue by benjaminran** [kubeshop/testkube-docker-action#5]
### What happened?

Hello, while trying to use testkube-docker-action to run a test with a custom executor and --args for the executor (parameters "locust-query --args='--dimension 768 -u 1 -t 10'"), it looks like the --args are getting incorrectly split by entrypoint.sh and some of them passed to testkube instead of the executor. The action is erroring with an error from testkube saying "error unknown shorthand flag: 'u' in -u" - but -u was intended for my executor.

I ran the same invocation against entrypoint.sh locally with bash -x, (invocation/full output in https://gist.github.com/benjaminran/de73c5b8b97f3ad9a7935ea456fc55be), and the local output shows:
```
 ++ kubectl testkube run test --namespace testkube locust-query '--args='\''--dimension' 768 -u 1 -t '10'\'''
```

Looks like word splitting is ignoring the single quotes for some reason and just splitting on all whitespace.

Do you have any guidance for me on this? Maybe the fix could be as simple as doing `result="$(eval "$cmdline")"` in entrypoint.sh, or handling args as an array throughout the script instead of a string--or maybe I'm missing something else. Thanks.

### Version

1.0.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vsukhin** [comment]
Hey, @benjaminran Let's try it out. We will be back to you soon. We do split by spaces and use lazy quotes

**Comment by benjaminran** [comment]
I'd expect this to fail too based on my understanding: https://github.com/kubeshop/helm-charts/blob/59054b87f83f890f4f62cf966ac63fd7e46de336/.github/workflows/testkube-docker-action.yaml#L61 - I think the 100 will get passed to testkube instead of the executor

**Comment by vsukhin** [comment]
sure, will check it out

**Comment by vsukhin** [comment]
confirming, for some reasons quotes are ignored, this call generates proper command to execute from shell, but it doesn't work in shell script
./entrypoint.sh "create" "test" "testkube" "" "" "--name locust-query --type cli/test --executor-args=\"--dimension 768 -u 1 -t 10\""

**Comment by vsukhin** [comment]
@benjaminran updated entrypoint.sh command call, at least, `./entrypoint.sh "create" "test" "testkube" "" "" "--name locust-query --type locust/test  --executor-args='--dimension 768 -u 1 -t 10'"` works locally
